repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        args: [--settings-path, config/.isort.cfg]

  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        args: [--config, config/pyproject.toml]

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: [--config, config/.flake8]
